---
- hosts: all
  tasks:

  - name: install open-iscsi
    pacman:
      name:
      - open-iscsi
    become: true

  - name: enable iscsid
    systemd:
      name: iscsid
      state: started
      enabled: true
    become: true

  - name: create k3s directory
    file:
      path: /opt/k3s/bin
      state: directory
      owner: root
      group: root
      mode: 0755
    become: true

  - name: download k3s binary
    get_url:
      # https://github.com/k3s-io/k3s/releases
      url: https://github.com/k3s-io/k3s/releases/download/v1.22.4%2Bk3s1/k3s
      dest: /opt/k3s/bin/k3s
      checksum: sha256:84bc5241f76d9468c25bb5982624df21ba7f1d6fb142d5986912dca82577d6f7
      mode: 0755
      owner: root
      group: root
    become: true
    notify:
    - restart k3s server

  - name: create k3s server systemd service
    copy:
      src: k3s/k3s.service
      dest: /etc/systemd/system/k3s.service
      owner: root
      group: root
      mode: 0644
    become: true
    notify:
    - restart k3s server

  - name: enable k3s server
    systemd:
      name: k3s
      state: started
      enabled: true
      daemon_reload: true
    become: true

  handlers:
  - name: restart k3s server
    systemd:
      name: k3s
      state: restarted
      daemon_reload: true
    become: true
