---
- hosts: all
  tasks:
  - name: uninstall iptables-nft
    pacman:
      name:
        - iptables
      state: absent
      force: true
    become: true

  - name: install iptables-nft
    pacman:
      name:
        - iptables-nft
    become: true

  - name: install kubernetes
    pacman:
      name:
        - conntrack-tools
        - docker
        - kubeadm
        - kubectl
        - kubelet
        - helm
    become: true

  - name: start docker
    systemd:
      name: docker
      state: started
      enabled: true
    become: true

  - name: create kubernetes directories
    file:
      path: "{{ item }}"
      state: directory
      owner: root
      group: root
      mode: '0755'
    with_items:
      - "/etc/kubernetes"
      - "/opt/kubernetes/bin"
    become: true

  - name: configure kubeadm
    copy:
      src: kubernetes/kubeadm/config.yaml
      dest: /etc/kubernetes/kubeadm.yaml
      owner: root
      group: root
      mode: '0644'
    become: true

  - name: enable kubelet
    systemd:
      service: kubelet
      state: started
      enabled: true
    become: true

  - name: initalize kubernetes
    script:
      cmd: kubernetes/kubeadm/init.sh
      creates: /etc/kubernetes/admin.conf

