---
- hosts: all
  tasks:
  - name: enable parallel downloads  # noqa risky-file-permissions
    ini_file:
      path: /etc/pacman.conf
      section: options
      option: ParallelDownloads
      value: "5"
    become: true

  - name: update pacman cache
    pacman:
      update_cache: true
    become: true

  - name: install pacman tools
    pacman:
      name: pacman-contrib
    become: true

  - name: install reflector
    pacman:
      name: reflector
    become: true

  - name: update pacman mirrorlist
    script: pacman/update-mirrorlist.sh
    become: true

  - name: install base metapackage
    pacman:
      name: base
    become: true

  - name: perform full upgrade
    pacman:
      upgrade: true
      update_cache: true
    notify:
    - reboot system
    become: true

  - name: install Intel microcode
    pacman:
      name: intel-ucode
    when: "'GenuineIntel' in ansible_processor"
    become: true
    notify:
    - reboot system

  - name: install AMD microcode
    pacman:
      name: amd-ucode
    when: "'AuthenticAMD' in ansible_processor"
    become: true
    notify:
    - reboot system

  - name: install firmware
    pacman:
      name: linux-firmware
    become: true
    notify:
    - reboot system

  handlers:
  - name: reboot system
    reboot:
    become: true
