apiVersion: kubeadm.k8s.io/v1beta3
kind: InitConfiguration
nodeRegistration:
  taints: []  # Taints are unecessary for single-node cluster
  ignorePreflightErrors:  # Needed for official Arch Linux Vagrant box
    - Swap
    - SystemVerification
skipPhases:
  - addon/kube-proxy  # Needed for Cilium kube-proxy replacement
---
kind: ClusterConfiguration
apiVersion: kubeadm.k8s.io/v1beta3
kubernetesVersion: v1.22.2
apiServer:
  certSANs:
    - "127.0.0.1"  # Needed for Vagrant external acccess
---
kind: KubeletConfiguration
apiVersion: kubelet.config.k8s.io/v1beta1
cgroupDriver: systemd
failSwapOn: false  # Needed for official Arch Linux Vagrant box
