---
apiVersion: v1
kind: Namespace
metadata:
  name: arma3
---
# https://community.bistudio.com/wiki/Arma_3:_Dedicated_Server
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: arma3
  namespace: arma3
  labels:
    app.kubernetes.io/name: arma3
    app.kubernetes.io/component: server
spec:
  replicas: 1
  serviceName: arma3
  selector:
    matchLabels:
      app.kubernetes.io/name: arma3
      app.kubernetes.io/component: server
  template:
    metadata:
      labels:
        app.kubernetes.io/name: arma3
        app.kubernetes.io/component: server
    spec:
      initContainers:
      - name: install
        image: steamcmd/steamcmd:ubuntu-20
        args:
        - +force_install_dir /opt/arma3
        - +login
        - "$(USERNAME)"
        - "$(PASSWORD)"
        - +app_update $(ARMA3_DEDICATED_SERVER_APPID)
        - +quit
        env:
        - name: ARMA3_DEDICATED_SERVER_APPID
          value: "233780"
        - name: USERNAME
          valueFrom:
            secretKeyRef:
              name: steam-account
              key: username
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: steam-account
              key: password
        volumeMounts:
        - name: steam
          mountPath: /root/.steam
        - name: arma3
          mountPath: /opt/arma3
      containers:
      - name: arma3
        image: ubuntu:20.04
        workingDir: /opt/arma3
        command:
        - /opt/arma3/arma3server_x64
        args:
        - -name=server
        - -config=/etc/arma3/server.cfg
        ports:
        - containerPort: 2302
          protocol: UDP
          name: game
        - containerPort: 2303
          protocol: UDP
          name: steam-query
        - containerPort: 2304
          protocol: UDP
          name: steam-master
        - containerPort: 2305
          protocol: UDP
          name: von
        - containerPort: 2306
          protocol: UDP
          name: battleye
        volumeMounts:
        - name: steam
          mountPath: /root/.steam
        - name: arma3
          mountPath: /opt/arma3
        - name: server-config
          mountPath: /etc/arma3
        - name: profiles
          mountPath: /root/.local/share/Arma 3 - Other Profiles/server
      - name: steamcmd
        image: steamcmd/steamcmd:ubuntu-20
        command:
        - /bin/bash
        - -c
        - "trap : TERM INT; sleep infinity & wait"
        env:
        - name: ARMA3_APPID
          value: "107410"
        - name: STEAM_USERNAME
          valueFrom:
            secretKeyRef:
              name: steam-account
              key: username
        - name: STEAM_PASSWORD
          valueFrom:
            secretKeyRef:
              name: steam-account
              key: password
        volumeMounts:
        - name: steam
          mountPath: /root/.steam
        - name: arma3
          mountPath: /opt/arma3
      hostNetwork: true  # Without this, some players behind Comcast CGNAT have problems connecting (?)
      volumes:
      - name: server-config
        secret:
          secretName: server-config
      - name: profiles
        configMap:
          name: profiles
  volumeClaimTemplates:
  - metadata:
      name: steam
      namespace: arma3
    spec:
      accessModes:
      - ReadWriteOnce
      storageClassName: longhorn
      resources:
        requests:
          storage: 2G
  - metadata:
      name: arma3
      namespace: arma3
    spec:
      accessModes:
      - ReadWriteOnce
      storageClassName: longhorn
      resources:
        requests:
          storage: 128G
  updateStrategy:
    type: OnDelete
---
# https://community.bistudio.com/wiki/Arma_3:_Headless_Client
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: arma3-headless-client
  namespace: arma3
  labels:
    app.kubernetes.io/name: arma3
    app.kubernetes.io/component: headless-client
spec:
  replicas: 1
  serviceName: arma3-headless-client
  selector:
    matchLabels:
      app.kubernetes.io/name: arma3
      app.kubernetes.io/component: headless-client
  template:
    metadata:
      labels:
        app.kubernetes.io/name: arma3
        app.kubernetes.io/component: headless-client
    spec:
      initContainers:
      - name: install
        image: steamcmd/steamcmd:ubuntu-20
        args:
        - +force_install_dir /opt/arma3
        - +login
        - "$(USERNAME)"
        - "$(PASSWORD)"
        - +app_update $(ARMA3_DEDICATED_SERVER_APPID)
        - +quit
        env:
        - name: ARMA3_DEDICATED_SERVER_APPID
          value: "233780"
        - name: USERNAME
          valueFrom:
            secretKeyRef:
              name: steam-account
              key: username
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: steam-account
              key: password
        volumeMounts:
        - name: steam
          mountPath: /root/.steam
        - name: arma3
          mountPath: /opt/arma3
      containers:
      - name: arma3
        image: ubuntu:20.04
        workingDir: /opt/arma3
        command:
        - /opt/arma3/arma3server_x64
        args:
        - -client
        - -connect=127.0.0.1
        - -password=$(ARMA3_SERVER_PASSWORD)
        env:
        - name: ARMA3_SERVER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: server-credentials
              key: password
        volumeMounts:
        - name: steam
          mountPath: /root/.steam
        - name: arma3
          mountPath: /opt/arma3
      - name: steamcmd
        image: steamcmd/steamcmd:ubuntu-20
        command:
        - /bin/bash
        - -c
        - "trap : TERM INT; sleep infinity & wait"
        env:
        - name: ARMA3_APPID
          value: "107410"
        - name: STEAM_USERNAME
          valueFrom:
            secretKeyRef:
              name: steam-account
              key: username
        - name: STEAM_PASSWORD
          valueFrom:
            secretKeyRef:
              name: steam-account
              key: password
        volumeMounts:
        - name: steam
          mountPath: /root/.steam
        - name: arma3
          mountPath: /opt/arma3
      hostNetwork: true  # Need to share network namespace with server due to headless client allowlist
      volumes:
      - name: server-credentials
        secret:
          secretName: server-credentials
  volumeClaimTemplates:
  - metadata:
      name: steam
      namespace: arma3
    spec:
      accessModes:
      - ReadWriteOnce
      storageClassName: longhorn
      resources:
        requests:
          storage: 2G
  - metadata:
      name: arma3
      namespace: arma3
    spec:
      accessModes:
      - ReadWriteOnce
      storageClassName: longhorn
      resources:
        requests:
          storage: 128G
  updateStrategy:
    type: OnDelete
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: steam-account
  namespace: arma3
stringData:
  username: "{{ arma3.steamcmd.username }}"
  password: "{{ arma3.steamcmd.password }}"
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: server-credentials
  namespace: arma3
stringData:
  password: "{{ arma3.server_password }}"
---
apiVersion: v1
kind: Secret
metadata:
  name: server-config
  namespace: arma3
stringData:
  # https://community.bistudio.com/wiki/Arma_3:_Server_Config_File
  server.cfg: |
    passwordAdmin = "{{ arma3.admin_password }}";
    password = "{{ arma3.server_password }}";
    serverCommandPassword = "{{ arma3.server_command_password }}";
    hostname = "{{ arma3.hostname }}";
    persistent = 1;
    disableVoN = 1;
    BattleEye = 0;
    statisticsEnabled = 0;
    // I found an issue with some mods (LAMBS, CUP ACE Weapons Compatibility)
    // where the .bisign client keys and .bikey server keys downloaded differ
    // between steamcmd on Linux and Steam on Windows. I'm not sure if this is
    // a Steam bug or mod bug. For now I've disable signature verification.
    verifySignatures = 0;
    headlessClients[] = {"127.0.0.1"};
    localClient[] = {"127.0.0.1"};
    forceDifficulty = "custom";
    // https://community.bistudio.com/wiki/Arma_3:_Server_Config_File#Server_Security
    allowedLoadFileExtensions[] = { "hpp","sqs","sqf","fsm","cpp","paa","txt","xml","inc","ext","sqm","ods","fxy","lip","csv","kb","bik","bikb","html","htm","biedi" };
    allowedPreprocessFileExtensions[] = { "hpp","sqs","sqf","fsm","cpp","paa","txt","xml","inc","ext","sqm","ods","fxy","lip","csv","kb","bik","bikb","html","htm","biedi" };
    allowedHTMLLoadExtensions[] = { "htm","html","xml","txt" };
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: profiles
  namespace: arma3
data:
  # https://community.bistudio.com/wiki/Arma_3:_Server_Config_File
  server.Arma3Profile: |
    class DifficultyPresets
    {
        class CustomDifficulty
        {
            class Options
            {
                /* Simulation */

                reducedDamage = 0;		// Reduced damage

                /* Situational awareness */

                groupIndicators = 0;	// Group indicators (0 = never, 1 = limited distance, 2 = always)
                friendlyTags = 0;		// Friendly name tags (0 = never, 1 = limited distance, 2 = always)
                enemyTags = 0;			// Enemy name tags (0 = never, 1 = limited distance, 2 = always)
                detectedMines = 0;		// Detected mines (0 = never, 1 = limited distance, 2 = always)
                commands = 0;			// Commands (0 = never, 1 = fade out, 2 = always)
                waypoints = 0;			// Waypoints (0 = never, 1 = fade out, 2 = always)
                tacticalPing = 0;		// Tactical ping (0 = disable, 1 = enable)

                /* Personal awareness */

                weaponInfo = 2;			// Weapon info (0 = never, 1 = fade out, 2 = always)
                stanceIndicator = 2;	// Stance indicator (0 = never, 1 = fade out, 2 = always)
                staminaBar = 1;			// Stamina bar
                weaponCrosshair = 0;	// Weapon crosshair
                visionAid = 0;			// Vision aid

                /* View */

                thirdPersonView = 1;	// 3rd person view (0 = disabled, 1 = enabled, 2 = enabled for vehicles only (Since  Arma 3 v1.99))
                cameraShake = 1;		// Camera shake

                /* Multiplayer */

                scoreTable = 0;			// Score table
                deathMessages = 0;		// Killed by
                vonID = 1;				// VoN ID

                /* Misc */

                mapContent = 0;			// Extended map content
                autoReport = 0;			// (former autoSpot) Automatic reporting of spotted enemied by players only. This doesn't have any effect on AIs.
                multipleSaves = 1;		// Multiple saves
            };

            // aiLevelPreset defines AI skill level and is counted from 0 and can have following values: 0 (Low), 1 (Normal), 2 (High), 3 (Custom).
            // when 3 (Custom) is chosen, values of skill and precision are taken from the class CustomAILevel.
            aiLevelPreset = 3;
        };

        class CustomAILevel
        {
            skillAI = 0.90;
            precisionAI = 0.35;
        };
    };
