# https://community.bistudio.com/wiki/Arma_3:_Dedicated_Server
---
apiVersion: v1
kind: Namespace
metadata:
  name: arma3
---
apiVersion: v1
kind: Service
metadata:
  name: arma3
  namespace: arma3
  labels:
    app.kubernetes.io/name: arma3
spec:
  type: NodePort
  ports:
  - name: game
    port: 2302
    protocol: UDP
    targetPort: game
    nodePort: 31302
  - name: steam-query
    port: 2303
    protocol: UDP
    targetPort: steam-query
    nodePort: 31303
  - name: steam-master
    port: 2304
    protocol: UDP
    targetPort: steam-master
    nodePort: 31304
  # VON port is reserved for legacy reasons, although the actual VON traffic
  # was moved to the game's port to work around NAT problems
  - name: von
    port: 2305
    protocol: UDP
    targetPort: von
    nodePort: 31305
  - name: battleye
    port: 2306
    protocol: UDP
    targetPort: battleye
    nodePort: 31306
  selector:
    app.kubernetes.io/name: arma3
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: arma3
  namespace: arma3
  labels:
    app.kubernetes.io/name: arma3
spec:
  serviceName: arma3
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: arma3
  template:
    metadata:
      labels:
        app.kubernetes.io/name: arma3
    spec:
      initContainers:
      - name: install
        image: steamcmd/steamcmd:ubuntu-20
        args:
        - +login
        - "$(USERNAME)"
        - "$(PASSWORD)"
        - +force_install_dir /opt/arma3
        - +app_update $(ARMA3_DEDICATED_SERVER_APPID)
        - +quit
        env:
        - name: ARMA3_DEDICATED_SERVER_APPID
          value: "233780"
        - name: USERNAME
          valueFrom:
            secretKeyRef:
              name: steam-account
              key: username
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: steam-account
              key: password
        volumeMounts:
        - name: steam
          mountPath: /root/.steam
        - name: arma3
          mountPath: /opt/arma3
      containers:
      - name: arma3
        image: ubuntu:20.04
        workingDir: /opt/arma3
        command:
        - /opt/arma3/arma3server_x64
        args:
        - -name=server
        - -config=/etc/arma3/server.cfg
        # Mods example:
        # - -mod=@cba_a3;@ace;@acre;@alive;@cup_weapons;@cup_weapons_ace;@cup_units;@cup_vehicles;@cup_vehicles_ace;@cup_terrains_core;@cup_terrains_maps;@cup_terrains_maps_2.0;@cup_terrains_cwa;@cup_terrains_ace;@dui_squad_radar;@enhanced_movement;@jsrs;@jsrs_cup_vehicles;@jsrs_cup_weapons;@lambs_danger.fsm;@zeus_enhanced;@zeus_enhanced_ace
        env:
        - name: STEAM_USERNAME
          valueFrom:
            secretKeyRef:
              name: steam-account
              key: username
        - name: STEAM_PASSWORD
          valueFrom:
            secretKeyRef:
              name: steam-account
              key: password
        ports:
        - containerPort: 2302
          protocol: UDP
          name: game
        - containerPort: 2303
          protocol: UDP
          name: steam-query
        - containerPort: 2304
          protocol: UDP
          name: steam-master
        - containerPort: 2305
          protocol: UDP
          name: von
        - containerPort: 2306
          protocol: UDP
          name: battleye
        volumeMounts:
        - name: steam
          mountPath: /root/.steam
        - name: arma3
          mountPath: /opt/arma3
        - name: server-config
          mountPath: /etc/arma3
        - name: profiles
          mountPath: /root/.local/share/Arma 3 - Other Profiles/server
      - name: steamcmd
        image: steamcmd/steamcmd:ubuntu-20
        command:
        - /bin/bash
        - -c
        - "trap : TERM INT; sleep infinity & wait"
        env:
        - name: ARMA3_APPID
          value: "107410"
        - name: STEAM_USERNAME
          valueFrom:
            secretKeyRef:
              name: steam-account
              key: username
        - name: STEAM_PASSWORD
          valueFrom:
            secretKeyRef:
              name: steam-account
              key: password
        volumeMounts:
        - name: steam
          mountPath: /root/.steam
        - name: arma3
          mountPath: /opt/arma3
      hostNetwork: true  # Without this, some players behind Comcast CGNAT have problems connecting (?)
      volumes:
      - name: server-config
        secret:
          secretName: server-config
      - name: profiles
        configMap:
          name: profiles
  volumeClaimTemplates:
  - metadata:
      name: steam
      namespace: arma3
    spec:
      accessModes:
      - ReadWriteOnce
      storageClassName: longhorn
      resources:
        requests:
          storage: 2G
  - metadata:
      name: arma3
      namespace: arma3
    spec:
      accessModes:
      - ReadWriteOnce
      storageClassName: longhorn
      resources:
        requests:
          storage: 192G
  updateStrategy:
    type: OnDelete
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: steam-account
  namespace: arma3
stringData:
  username: "{{ arma3.steamcmd.username }}"
  password: "{{ arma3.steamcmd.password }}"
---
apiVersion: v1
kind: Secret
metadata:
  name: server-config
  namespace: arma3
stringData:
  # https://community.bistudio.com/wiki/Arma_3:_Server_Config_File
  server.cfg: |
    passwordAdmin = "{{ arma3.admin_password }}";
    password = "{{ arma3.server_password }}";
    serverCommandPassword = "{{ arma3.server_command_password }}";
    hostname = "{{ arma3.hostname }}";
    disableVoN = 1;
    BattleEye = 0;
    statisticsEnabled = 0;
    verifySignatures = 0;
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: profiles
  namespace: arma3
data:
  server.Arma3Profile: |
    class DifficultyPresets
    {
        class CustomDifficulty
        {
            class Options
            {
                /* Simulation */

                reducedDamage = 0;		// Reduced damage

                /* Situational awareness */

                groupIndicators = 0;	// Group indicators (0 = never, 1 = limited distance, 2 = always)
                friendlyTags = 0;		// Friendly name tags (0 = never, 1 = limited distance, 2 = always)
                enemyTags = 0;			// Enemy name tags (0 = never, 1 = limited distance, 2 = always)
                detectedMines = 0;		// Detected mines (0 = never, 1 = limited distance, 2 = always)
                commands = 0;			// Commands (0 = never, 1 = fade out, 2 = always)
                waypoints = 0;			// Waypoints (0 = never, 1 = fade out, 2 = always)
                tacticalPing = 1;		// Tactical ping (0 = disable, 1 = enable)

                /* Personal awareness */

                weaponInfo = 2;			// Weapon info (0 = never, 1 = fade out, 2 = always)
                stanceIndicator = 2;	// Stance indicator (0 = never, 1 = fade out, 2 = always)
                staminaBar = 1;			// Stamina bar
                weaponCrosshair = 0;	// Weapon crosshair
                visionAid = 0;			// Vision aid

                /* View */

                thirdPersonView = 1;	// 3rd person view (0 = disabled, 1 = enabled, 2 = enabled for vehicles only (Since  Arma 3 v1.99))
                cameraShake = 1;		// Camera shake

                /* Multiplayer */

                scoreTable = 0;			// Score table
                deathMessages = 0;		// Killed by
                vonID = 1;				// VoN ID

                /* Misc */

                mapContent = 0;			// Extended map content
                autoReport = 0;			// (former autoSpot) Automatic reporting of spotted enemied by players only. This doesn't have any effect on AIs.
                multipleSaves = 1;		// Multiple saves
            };

            // aiLevelPreset defines AI skill level and is counted from 0 and can have following values: 0 (Low), 1 (Normal), 2 (High), 3 (Custom).
            // when 3 (Custom) is chosen, values of skill and precision are taken from the class CustomAILevel.
            aiLevelPreset = 3;
        };

        class CustomAILevel
        {
            skillAI = 0.90;
            precisionAI = 0.25;
        };
    };
